BP-2797   Add possibility to change Channel header
buckaroo-it/BuckarooSDK_PHP pull request #134
Opened 2023-07-27 13:00 UTC by SandervdHulst

2023-07-28 07:42 UTC, harli91 approved these changes

2023-07-28 08:09 UTC, Rinor12010 requested changes

2023-07-28 08:09 UTC, Rinor12010 commented on src/Models/Payload/Payload.php
Config parameters are not needed in the payload model since we are only changing them from the config

2023-08-10 07:06 UTC, Rinor12010 approved these changes

2023-08-10 09:02 UTC, merged