Php Clean code format PSR-12
buckaroo-it/BuckarooSDK_PHP pull request #67
Opened 2023-01-12 10:38 UTC by abeka-buckaroo

2023-01-13 14:40 UTC, vegimcarkaxhija commented on src/PaymentMethods/KlarnaPay/Models/Recipient.php
> -use Buckaroo\Models\{Address, Company, Email, Person, Phone, ServiceParameter};
for me this one is more readable

2023-01-13 14:41 UTC, vegimcarkaxhija commented on src/PaymentMethods/PaymentMethodFactory.php
> -        ApplePay::class                 => ['applepay'],
for me this is more readable

2023-01-13 15:38 UTC, Rinor12010 commented on src/Handlers/Reply/ReplyHandler.php
>              return $this->data[$key] ?? $this->data[strtolower($key)] ?? $this->data[strtoupper($key)] ?? null;
When making comparisons of more than 2 variables break them to multiple lines

2023-01-13 15:38 UTC, Rinor12010 commented on src/Models/ServiceList.php
The shorter version is better

2023-01-13 15:38 UTC, Rinor12010 commented on src/PaymentMethods/Billink/Models/Recipient.php
The shorter version is better

2023-01-13 15:38 UTC, Rinor12010 commented on src/PaymentMethods/CreditManagement/Models/Invoice.php
The shorter version is better

2023-01-13 15:38 UTC, Rinor12010 commented on src/PaymentMethods/KlarnaPay/Models/Recipient.php
The shorter version is better

2023-01-13 15:38 UTC, Rinor12010 commented on src/PaymentMethods/PaymentMethodFactory.php
>      ];
The original format is better

2023-01-13 15:38 UTC, Rinor12010 commented on src/PaymentMethods/Tinka/Models/Recipient.php
The shorter version is better

2023-01-16 12:20 UTC, harli91 approved these changes

2023-01-17 08:22 UTC, ShuCh3n requested changes

2023-01-17 08:22 UTC, ShuCh3n commented on src/BuckarooClient.php
> -        {
My personal preference is to have brackets on the next line. This way, it's easier to see where it starts.

2023-01-17 08:22 UTC, ShuCh3n commented on src/Models/ServiceList.php
> -use Buckaroo\Services\ServiceListParameters\{DefaultParameters, ModelParameters, ServiceListParameter};
A grouped declaration is easier to read.

2023-01-19 15:29 UTC, ShuCh3n approved these changes

2023-01-19 15:30 UTC, merged